### ISSUE TITLE
Navigation bar crashes

### ISSUE THREAD

**Issue by frandavid100** [epodegrid/epd106-ADB#2]
Hi,

Thanks for the guide. Everything works properly, except the navigation bar part. Firstly because the apk file [isn't there anymore](https://github.com/epodegrid/epd106-ADB/issues/1) but also because if you install any other navigation app, and then try to give it permission to be over other apps, it always crashes. 

![IMG_20200518_122413](https://user-images.githubusercontent.com/694794/82207186-b9d94200-9909-11ea-912f-4b33a82a6dd0.jpg)

![IMG_20200518_122423](https://user-images.githubusercontent.com/694794/82207182-b80f7e80-9909-11ea-8c93-d250a3845d32.jpg)

Is there any way to solve this?

**Comment by epodegrid** [comment]
Thank you for letting me know that the navigation bar apk was not available. I've reuploaded the file at [Mega](https://mega.nz/file/zV5liQQZ#jAYeARU4YnnQmGo6AsLmRDf9x3T4DpmOIL5vJT_1MSg).  

I've tried some of the other apps for navigation bar apps such as Fluid Navigation Gestures but it's often more complicated to set up, and the battery consumption also increases because the screen needs to refresh many times to run an app that was not intended for an e-ink screen. Hence, I've used the Xiaomi Navigation Button, which was a port of the navigation button from MIUI. This is just a button and does not consume much power and causes no trouble for regular use. Also, there is not much screen refresh needed and things work as expected. I suppose that the system force closes the app you've tried because they don't fit well with the screen and the device's resources might be strained. Coming to the permissions, the device is running a very skimmed version of Android, and not everything is available. If only the system files were available, something could be done, maybe root access? 

For now, I would suggest that you uninstall the navigation apps and use the Xiaomi Button. I'll also try to get something working and if everything goes well, I'll update the guide.

**Comment by epodegrid** [comment]
> Hi,
> 
> Thanks for the guide. Everything works properly, except the navigation bar part. Firstly because the apk file [isn't there anymore](https://github.com/epodegrid/epd106-ADB/issues/1) but also because if you install any other navigation app, and then try to give it permission to be over other apps, it always crashes.
> 
> ![IMG_20200518_122413](https://user-images.githubusercontent.com/694794/82207186-b9d94200-9909-11ea-912f-4b33a82a6dd0.jpg)
> 
> ![IMG_20200518_122423](https://user-images.githubusercontent.com/694794/82207182-b80f7e80-9909-11ea-8c93-d250a3845d32.jpg)
> 
> Is there any way to solve this?

Could you also provide me the crash logs? That'll be a great help!

**Comment by epodegrid** [comment]
> > Hi,
> > Thanks for the guide. Everything works properly, except the navigation bar part. Firstly because the apk file [isn't there anymore](https://github.com/epodegrid/epd106-ADB/issues/1) but also because if you install any other navigation app, and then try to give it permission to be over other apps, it always crashes.
> > Is there any way to solve this?
> 
> Could you also provide me the crash logs? That'll be a great help!

**Comment by epodegrid** [comment]
> Hi,
> 
> Thanks for the guide. Everything works properly, except the navigation bar part. Firstly because the apk file [isn't there anymore](https://github.com/epodegrid/epd106-ADB/issues/1) but also because if you install any other navigation app, and then try to give it permission to be over other apps, it always crashes.

> Is there any way to solve this?

Could you also provide me the crash logs? That'll be a great help!
