### ISSUE TITLE
I made a little script a week before you wrote this tutorial

### ISSUE THREAD

**Issue by drago06** [epodegrid/epd106-ADB#3]
Hello, I made a script that includes basic app installation and doesn't require installing adb to your pc. Also, there is the installationof navigation gestures and language change, not only to English but to whatever language you want. You can see when I posted it on the 4pda thread of the device, my nickname there is leo06. You can download it from [this post](https://4pda.ru/forum/index.php?showtopic=973615&view=findpost&p=96408743)

**Comment by epodegrid** [comment]
Thanks for the work. All this ADB stuff was a bit complicated for some and I think your script could be a great help for all. Unfortunately, I have not been able to download the script because it was deleted from 4pda. Do you mind uploading it again? I could also mirror a MEGA link and add your work on the page.

As a second note, have you been able to extract the boot.img/recovery.img from the device? I have been trying to do it for some time, to get root access, but it doesn't work.

**Comment by epodegrid** [comment]
> Hello, I made a script that includes basic app installation and doesn't require installing adb to your pc. Also, there is the installationof navigation gestures and language change, not only to English but to whatever language you want. You can see when I posted it on the 4pda thread of the device, my nickname there is leo06. You can download it from [this post](https://4pda.ru/forum/index.php?showtopic=973615&view=findpost&p=96408743)

Thanks for the work. All this ADB stuff was a bit complicated for some and I think your script could be a great help for all. Unfortunately, I have not been able to download the script because it was deleted from 4pda. Do you mind uploading it again? I could also mirror a MEGA link and add your work on the page.

As a second note, have you been able to extract the boot.img/recovery.img from the device? I have been trying to do it for some time, to get root access, but it doesn't work.

**Comment by drago06** [comment]
I tried 4pda now and was able to download it successfully. Anyway, [here's the mega link](https://mega.nz/file/1Z9nAK5L) 
No, I wasn't able to root it, and I don't think it's possible since the software is preinstalled on the chipset, in fact if you go to the Allwinner site and find b300 model, it says that it has android 8.1 preinstalled. And also, I didn't manage to get Allwinner tools working with it

**Comment by epodegrid** [comment]
> I tried 4pda now and was able to download it successfully. Anyway, [here's the mega link](https://mega.nz/file/1Z9nAK5L)
> No, I wasn't able to root it, and I don't think it's possible since the software is preinstalled on the chipset, in fact if you go to the Allwinner site and find b300 model, it says that it has android 8.1 preinstalled. And also, I didn't manage to get Allwinner tools working with it

The mega link is without the decryption key and I can't access it. Please send the decryption key or add the link with decryption. 4PDA still gives me a 404 on the download.

I think it's possible to gain a systemless root. But in any case, editing the boot image would need to needed. The e-reader is running on treble A only, 32 bit. My idea was to wait for an upcoming update and then extract the update for the boot image. But I don't know where the device is saving update files.

**Comment by drago06** [comment]
Try [this](https://mega.nz/file/NNl3AKLb#NSNVkmM3sitPICBBwi2UuV2g1vygS1Ftr22W2D9jTZQ) one. 
I just found out that it has fastboot, so you are right, it is possible. I saw the treble thing too, but you'd need to implement the eink compatibility layer to get the contrast regulation and maybe  backlight regulation won't work without it too.

**Comment by drago06** [comment]
And anyway, the real problem is unlocking the bootloader

**Comment by epodegrid** [comment]
Thanks for the link! I've updated the tutorial. 

I entered both fastboot and recovery mode, nothing useful. Yore're right, the surprising part is that even if OEM bootloader unlock option is on, the device doesn't take any command after booting into fastboot, forget unlocking the bootloader. Don't know why it does that.

**Comment by drago06** [comment]
I'll look better into it. Have you figured out what's that little button near the usb c port? Could be a key for unlocking or something

**Comment by Feat44** [comment]
@drago06 I installed epodegrid's package and now I want to install yours. When I start the script it just shows me that it can't find any devices/emulators. Although USB MTP Mode is on. Do you have any suggestions?
