### ISSUE TITLE
Change Lock Screen / Screen Saver

### ISSUE THREAD

**Issue by yancyn** [epodegrid/epd106-ADB#4]
_\*\*This is not a bug but a new request\*\*_

Currently the screen saver/lockscreen keep changing from few animal picture (eagle, polar bear, panda) when going into sleeping mode or not in use. Wondering if we can change the lockscreen to a static calendar or our picture so that it turn to become a photo frame or calendar when not in use. This is more useful than displaying an animal picture 😺 

Since a static lockscreen image almost not consuming any power.

## What I've tried
1. Set the device never go to sleep. Sideload a live wallpaper app and make it display when not in use. But this drain up my battery.
2. Install a wallpaper changer app (i.e. [Wallpaper Changer](https://play.google.com/store/apps/details?id=de.j4velin.wallpaperChanger)) and set to display as calendar with a static photo. However the app failed to activate because complains there are no Livewapper feature on device (Android 8.1).

This is what I've tried. Hope can give you better insight and save your time or trying.

**Comment by epodegrid** [comment]
Thanks for your input!

I tried some ways and none worked. 

1.  First, I tried Nova Launcher, and that crashes on setting lock screen wallpaper. 

2. Setting the wallpaper using ADB, but there's absolutely no wallpaperPickerService like other android devices.

3. Locating the stock images, and then replacing them. But the system denies any access to root directory. 

### What might work: Rooting the device. 

I have tried to pull the boot.img / recovery.img from the system multiple time but it just doesn't show a recovery partition, because of the "systemless". These are the partitions:
   1        0       8192 ram0
   1        1       8192 ram1
   1        2       8192 ram2
   1        3       8192 ram3
   1        4       8192 ram4
   1        5       8192 ram5
   1        6       8192 ram6
   1        7       8192 ram7
   1        8       8192 ram8
   1        9       8192 ram9
   1       10       8192 ram10
   1       11       8192 ram11
   1       12       8192 ram12
   1       13       8192 ram13
   1       14       8192 ram14
   1       15       8192 ram15
 254        0     705664 zram0
 179        0   15106048 mmcblk0
 179        1   13037551 mmcblk0p1
 179        2      32768 mmcblk0p2
 179        3      16384 mmcblk0p3
 179        4      32768 mmcblk0p4
 179        5    1048576 mmcblk0p5
 179        6     245760 mmcblk0p6
 179        7      16384 mmcblk0p7
 179        8      32768 mmcblk0p8
 179        9     524288 mmcblk0p9
 179       10      16384 mmcblk0p10
 179       11      16384 mmcblk0p11
 179       12        512 mmcblk0p12
 179       13      15872 mmcblk0p13
 179       14      16384 mmcblk0p14
 179       15      16384 mmcblk0p15
 179       48       4096 mmcblk0rpmb
 179       32       4096 mmcblk0boot1
 179       16       4096 mmcblk0boot0


If you could try something related and manage to do more with this device, please let me know!
